### ISSUE TITLE
What is Logger.controlName intended for?

### ISSUE THREAD

**Issue by karelkral** [h2floh/azure-dev-ops-react-ui-unit-testing#13]
There is a constructor parameter `controlName` in `Logger.ts`. But this parameter is never used nor referenced. What was the intention for this parameter? Should be used as property for appInsights? 
https://github.com/h2floh/azure-dev-ops-react-ui-unit-testing/blob/main/src/Shared/Logger/Logger.ts

Thanks for the excellent sample.

**Comment by h2floh** [comment]
Hi @karelkral sorry for late response. Mhh you are absolutely right, it should be used as a property / additional info for appInsights or the console logger. I think it got lost in some refactoring action. Let me check on it.

**Comment by karelkral** [comment]
Just a note: It is not a good idea to use `this.constructor.name` as controlName. JavaScript get minified in production and `this.constructor.name` returns some minified version of control name as "M",

**Comment by h2floh** [comment]
Thanks for the insights! Was not aware of that. Let's fix that later too.

**Comment by h2floh** [comment]
Hi @karelkral , I guess [these changes](https://github.com/h2floh/azure-dev-ops-react-ui-unit-testing/pull/19/files) should fix the issue you mentioned? Any better idea?

**Comment by karelkral** [comment]
Agree, I am also using string literal as a control name.

**Comment by h2floh** [comment]
Fixed with #19
